Homework1
made-ml-in-prod-2021/viconstel pull request #2
Opened 2021-05-09 20:07 UTC by viconstel

В данном проекте рассматривалась задача классификации Heart Disease UCI (https://www.kaggle.com/ronitf/heart-disease-uci). В качестве моделей классификации были выбраны логистическая регрессия и k-NN. CSV-файлы с данными для обучения и тестирования расположены в директории data. В папке configs находятся файлы конфигурации для настройки параметров выбранных моделей, путей файлов с данными и файлов для хранения артефактов обучения, а также файл настройки логирования. Файлы с исходным кодом для чтения датасетов, разделения на трейн/валидационную части, файлы сущностей из файлов конфигурации, препроцессинга данных, работы с моделью и запуска всего пайплайна расположены в папке ml_project. После обучения артефакты помещаются в директорию models. Jupyter ноутбук с EDA помещен в папку notebooks. Для препроцессинга категориальных признаков использованы SimpleImputer и OneHotEncoder, а для предобработки числовых данных SimpleImputer и кастомный StandardScaler, код для его тестирования находится в папке tests. Для оценки качества обученной модели используются метрики accuracy score и F1 score. Более подробное описание проекта, включая процедуру запуска и структуру проекта, можно посмотреть в файле README.md.

2021-05-10 17:17 UTC, EvgeniiMunin reviewed
Есть комментарии по кастомному StandardScaler'у + мелкие замечания.Также лучше было бы прописать тесты для модели, фичей, данных и пайплайна. В остальном код качественный без особых недочетов. Думаю, что оценка на самопроверке вполне обоснована.

2021-05-10 17:17 UTC, EvgeniiMunin commented on homework1/configs/logreg_config.yml
> +  solver: "lbfgs"
Для аттрибутов лучше использовать snake_case (вместо С)

2021-05-10 17:17 UTC, EvgeniiMunin commented on homework1/ml_project/run_pipeline.py
> +    train_pipeline_command()
Вызов train_pipeline_command происходит без аргументов. Для config_path, train_val нужно задать дефолтные значения.

2021-05-10 17:17 UTC, EvgeniiMunin commented on homework1/ml_project/features/build_features.py
> +        return data
Как обрабатывается случай деления на 0, если СКО в данных (например в константной колонке) self.std = 0 ?

2021-05-10 17:17 UTC, EvgeniiMunin commented on homework1/tests/test_custom_scaler.py
> +import numpy as np
Лучше сначала написать импортирование библиотек, потом определение констант

2021-05-10 17:17 UTC, EvgeniiMunin commented on homework1/tests/test_custom_scaler.py
> +import pytest
Если pytest не был использован, то лучше его не импортировать. Неиспользуемые библиотеки лучше не импортить

2021-05-12 13:46 UTC, viconstel commented
Исправлены следующие замечания:
1. Убран импорт неиспользуемой библиотеки pytest.
2. Вместо прописывания пути для импорта в sys.path используется команда "pip install -e ." с использованием файла setup.py. Константа объявляется после импортов.
3.  Добавлена обработка случая нулевого среднеквадратического отклонения и тест на корректную обработку этого случая. Если std равно 0, ему присваивается значение 1 по аналогии с реализацией StandardScaler в библиотеке Scikit-learn.
4. Заданы дефолтные значения для аргументов config_path и train_val.
5. Название параметра "C" для логистической регрессии изменено на "inverse_regularization_strength" согласно snake_case именованию.

2021-05-17 10:27 UTC, kindofman requested changes

2021-05-17 10:27 UTC, kindofman commented on homework1/requirements.txt
> +zipp==3.4.1
Для того, чтобы запустился ноутбук не хватает библиотек jupyter, matplotlib, seaborn.

2021-05-17 10:27 UTC, kindofman commented on homework1/configs/knn_config.yml
> +output_model_path: "models/model.pkl"
Поправь, пожалуйста, пути в конфигах, чтобы все запускалось. Например, models/model.pkl => ml_project/models/model.pkl.

2021-05-17 11:56 UTC, viconstel commented
1. Добавил jupyter, matplotlib и seaborn в файл requirements.txt.
2. В директории ml_project/models лежит py-файл с исходным кодом модели. Для хранения артефактов после обучения добавил пустую директорию models в корневой папке проекта, аналогичному тому, как показывалось на занятии в примере с Cookiecutter DS template. Пути в конфигах не менял, проект запускается успешно.

2021-05-23 10:29 UTC, kindofman approved these changes
Хорошая работа.

25 баллов.

2021-05-23 10:40 UTC, EvgeniiMunin approved these changes

2021-05-23 10:40 UTC, EvgeniiMunin commented
Approved

2021-05-23 14:29 UTC, merged