Homework2
made-ml-in-prod-2021/viconstel pull request #3
Opened 2021-05-19 12:08 UTC by viconstel

Файлы домашнего задания №2 расположены в директории /online_inference. Обученная в ДЗ №1 модель LogisticRegression обернута в REST-сервис на основе FastAPI для inference в режиме онлайн. Исходный код сервиса находится в файле app.py. Тесты для сервиса расположены в файле tests/test_app.py. Скрипт для опроса сервиса с использованием данных обучающей выборки из ДЗ №1 содержится в файле make_request.py. Файл Dockerfile описывает слои для образа данного REST-сервиса. Более подробная информация находится в файле README.md.

2021-05-22 09:29 UTC, alex-tikh requested changes

2021-05-22 09:29 UTC, alex-tikh commented on online_inference/make_request.py
> +DIR_PATH = '../homework1'
Лучше прописать эти пути в переменные окружения докер файла

2021-05-22 09:29 UTC, alex-tikh commented on online_inference/app.py
>  CONFIG_PATH = r'configs/logreg_config.yml'
Лучше перенести эти переменные в переменные окружения докер файла

2021-05-22 09:29 UTC, alex-tikh commented on online_inference/tests/test_app.py
> +CORRECT_DATA_SAMPLE = [
Данные лучше генерировать с помощью fixture

2021-05-22 09:29 UTC, alex-tikh commented on online_inference/app.py
> +from ml_project.entities import read_pipeline_params
Лучше убрать все зависимости от ml_project, добавить в этот проект все необходимые source файлы. Сейчас слишком сложная структура, такой проект будет тяжело поддерживать. 
Создать свой requirements.txt, не тянуть ненужные либы

2021-05-22 09:29 UTC, alex-tikh commented on online_inference/Dockerfile
>  FROM python:3.7
Как облегчить докер образ:
- почитай про docker base images for python 
- используй pip без кэширования при сборке образа
- создай собственный облегченный requirements.txt для этого проекта

За каждый пункт +1 балл за облегчение докер образа

2021-05-23 12:54 UTC, Mikhail-M requested changes
в реквесте код первой дз, добейтесь, чтобы его не было

2021-05-24 10:55 UTC, viconstel commented
Убрал код первого дз. Для этого пришлось закрыть и переоткрыть pull request. Другого способа не нашел

2021-05-30 21:27 UTC, viconstel commented
Внес следующие изменения:
1. В файле app.py добавил пути в переменные окружения докер файла. В файле make_request.py пути не менял, так как данный файл не включается в докер образ.
2. В файле test_app.py данные теперь генерируются с помощью pytest fixture.
3. Убрана зависимость от ml_project, для этого были внесены изменения в исходные файлы проекта и необходимые для работы файлы были добавлены в Dockerfile.
4. Облегчил докер образ. До изменений размер образа был 1.48 gb. Выполнил следующие изменения:
- Использовал новый облегченный файл requirements.txt. (Размер снизился до 1.31 gb).
- Использовал флаг --no-cache-dir при команде RUN pip в Dockerfile. (Размер снизился до 1.22 gb).
- Использовал python:3.7-slim-stretch base image. (Размер снизился до 436 mb).

2021-06-01 07:31 UTC, Mikhail-M commented
> Убрал код первого дз. Для этого пришлось закрыть и переоткрыть pull request. Другого способа не нашел

мне непонятно почему так. , все делается просто коммитами

2021-06-01 07:41 UTC, viconstel commented
Новые коммиты добавляются к уже существующим в пулл реквесте. А старые (код первой дз) не модифицируются. Возможно делал что-то неправильно.

2021-06-01 08:01 UTC, Mikhail-M approved these changes
Баллы: 19*0.6 = 11.4

2021-06-01 08:06 UTC, viconstel commented
> Баллы: 19*0.6 = 11.4
Скажите, пожалуйста, за что поставлен штраф? Домашнее задание со всем кодом было сдано до soft дедлайна. Это можно отследить по времени пулл реквеста и по правкам кода от Вас и alex-tikh.

2021-06-01 08:08 UTC, Mikhail-M approved these changes
Баллы: 19

Ошибся

2021-06-01 08:09 UTC, viconstel commented
> Баллы: 19
> 
> Ошибся

Спасибо!

2021-06-04 18:00 UTC, merged